apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pvbouwel/peter_argo_test.git
    path: charts/spark-operator-wrapper
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
