apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pvbouwel/peter_argo_test.git
    path: charts/zookeeper-wrapper
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - values-{{ .Values.env }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: zookeeper{{ .Values.env }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
